#
# Author:linrol
#

version: '3'

services:
  coupon:
    build:
      context: .
      args:
        - PROJ_NAME=$JOB_BASE_NAME
      dockerfile: Dockerfile
    image: coupon
    container_name: coupon
    ports:
      - 8074:8074
    restart: always
    volumes:
      - /root/web/app/coupon/:/root/web/app/coupon/
      - /usr/local/java/jdk1.8.0_201/:/usr/local/java/jdk1.8.0_201/
    environment:
      - JAVA_OPTS=-Xmx512m -Xms256m -XX:MetaspaceSize=64M -XX:MaxMetaspaceSize=256M
    entrypoint:
      java ${JAVA_OPTS} -Ddataoke.appKey=612c6a2e0bd07 -Ddataoke.appSecret=51051d602280c91fe2f03452de065d63 -Dspring.datasource.username=root -Dspring.datasource.password=19941208 -Dspring.redis.password=linrol_redis -jar ${JOB_BASE_NAME}.jar --spring.profiles.active=prod
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 768M
        reservations:
          memory: 256M